-- Expand ArtistCategory enum with new creative disciplines
ALTER TYPE "ArtistCategory" ADD VALUE IF NOT EXISTS 'BAILARIN';
ALTER TYPE "ArtistCategory" ADD VALUE IF NOT EXISTS 'VIDEOGRAFO';
ALTER TYPE "ArtistCategory" ADD VALUE IF NOT EXISTS 'DISENADOR';
ALTER TYPE "ArtistCategory" ADD VALUE IF NOT EXISTS 'ESCRITOR';
ALTER TYPE "ArtistCategory" ADD VALUE IF NOT EXISTS 'ANIMADOR';
ALTER TYPE "ArtistCategory" ADD VALUE IF NOT EXISTS 'MAGO';
ALTER TYPE "ArtistCategory" ADD VALUE IF NOT EXISTS 'ACROBATA';
