apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace: ingress-nginx (different from the app namespace "piums")
# Apply separately:  kubectl apply -k infra/k8s/ingress-nginx/
namespace: ingress-nginx

resources:
  - configmap.yaml

patches:
  - path: service-patch.yaml
    target:
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
